apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: transformer-cronjob
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: transformer-cronjob
            image: egovio/transformer-cronjob
            command: ["python3","transformer.py"] 
            env:
              - name: ES_HOST_URL
                valueFrom:
                  configMapKeyRef:
                    name: egov-config
                    key: es-indexer-host
              - name: ES_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: elasticsearch-credential
                    key: username
              - name: ES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: elasticsearch-credential
                    key: password
              - name: ES_PI_INDEX
                value: "ifms-pi-index"
              - name: ES_INDIVIDUAL_INDEX
                value : "individual-index-v1"
              - name: ES_TRANSFORMER_PI_INDEX
                value: "transform-ifms-pi-index"
          restartPolicy: OnFailure